from __future__ import annotations

DOMAIN = "proscenic"
MANUFACTURER = "Proscenic"
DEFAULT_NAME = "Proscenic"

# Tuya protocol
TUYA_PROTOCOL_VERSION = 3.3

# Config keys (entry.data)
CONF_DEVICE_ID = "device_id"
CONF_LOCAL_KEY = "local_key"
CONF_HOST = "host"
CONF_NAME = "name"

# Options (entry.options)
CONF_SCAN_INTERVAL = "scan_interval"
CONF_REMEMBER_FAN_SPEED = "remember_fan_speed"
CONF_SHOW_RAW_DPS = "show_raw_dps"
CONF_AUTO_DISCOVER_IP = "auto_discover_ip"

DEFAULT_SCAN_INTERVAL_SECONDS = 10
DEFAULT_REMEMBER_FAN_SPEED = False
DEFAULT_SHOW_RAW_DPS = False
DEFAULT_AUTO_DISCOVER_IP = True

# seconds
REMEMBER_FAN_SPEED_DELAY = 6

# DPS (850T)
DP_POWER = 1
DP_FAULT = 11
DP_CLEANING_MODE = 25
DP_DIRECTION_CONTROL = 26
DP_FAN_SPEED = 27
DP_CURRENT_STATE = 38
DP_BATTERY = 39
DP_CLEAN_RECORD = 40
DP_CLEAN_AREA = 41
DP_CLEAN_TIME = 42
DP_SENSOR_HEALTH = 44
DP_FILTER_HEALTH = 45
DP_SIDE_BRUSH_HEALTH = 47
DP_BRUSH_HEALTH = 48
DP_SWEEP_OR_MOP = 49
DP_RESET_FILTER = 52
DP_DEVICE_MODEL = 58
DP_WATER_SPEED = 60